name: Continuous Integration

on: 
  push:
    branches: [main,]
  pull_request:
    branches: [main]

jobs:
  buildWindows:
    name: Windows Build
    runs-on: windows-2022
    environment: sign
    env:
      Solution: AVMHomeAutomation.sln
      NugetSpc: AVMHomeAutomation.nuspec

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Add SignKeys
      uses: Bassman2/SignKey@v1
      with:
        file: Bassman.snk
        key: ${{ secrets.SIGNKEY }}
        
    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1

    - name: Cache packages  
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-
      
    - name: Nuget restore dependencies
      run: nuget restore $env:Solution

    - name: Dotnet restore dependencies
      run: dotnet restore $env:Solution

    - name: MSBuild of solution
      run: msbuild $env:Solution /p:configuration="Debug" /verbosity:minimal   

    - name: MSBuild of solution
      run: msbuild $env:Solution /p:configuration="Release" /verbosity:minimal   
        
    - name: Nuget pack nuspec
      working-directory: .\Nuget\
      run: nuget pack $env:NugetSpc -properties Configuration=Release
      
    - name: Upload documentation artifact     
      uses: actions/upload-artifact@v3
      with:
        name: Documentation.zip
        path: Doc/AVMHomeAutomationDoc/Help/AVMHomeAutomation.chm
        
    - name: Upload nuget pack artifact     
      uses: actions/upload-artifact@v3
      with:
        name: NugetPackage.zip
        path: Nuget/AVMHomeAutomation.*.nupkg
        
  buildLinux:
    name: Linux Build
    runs-on: ubuntu-22.04
    environment: sign
    env:
      Solution: AVMHomeAutomation.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Src/AVMHomeAutomation70/AVMHomeAutomation70.csproj
    
    - name: Build
      run: dotnet build Src/AVMHomeAutomation70/AVMHomeAutomation70.csproj --no-restore
     
       
  buildMac:
    name: MacOS Build
    runs-on: macos-12
    environment: sign
    env:
      Solution: AVMHomeAutomation.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Src/AVMHomeAutomation70/AVMHomeAutomation70.csproj
    
    - name: Build
      run: dotnet build Src/AVMHomeAutomation70/AVMHomeAutomation70.csproj --no-restore